Added WinUI3 package MicrosoftToolkit.WinUI.Lottie
CommunityToolkit/Lottie-Windows pull request #500
Opened 2022-05-24 19:42 UTC by aborziak-ms

Added project for WinUI3 package.

2022-05-24 20:10 UTC, raymond-wh-leung commented on source/Lottie/LottieVisualOptions.cs
> +namespace MicrosoftToolkit.WinUI.Lottie
>MicrosoftToolkit [](http://example.com/codeflow?start=10&length=16)

Wondering why MicrosoftToollKit instead of Microsoft.TooKit?

2022-05-24 20:42 UTC, aborziak-ms commented on source/Lottie/LottieVisualOptions.cs
> +namespace MicrosoftToolkit.WinUI.Lottie
Oh, sure, it is a new naming convention for **WinUI3** packages in **CommunityToolkit** organization:

"_As part of this release, we’re introducing a new Package Root for the Windows Community Toolkit on NuGet: CommunityToolkit.*. We’ve updated our namespaces and packages from **Microsoft.Toolkit.Uwp.*** to now be **CommunityToolkit.WinUI.***. We’re making this migration now as part of our WinUI 3 update, as having our package identity allows us to better maintain our packages and their ownership with the community. In the future, it also allows us more flexibility to work with other groups and technologies to share branding and ownership of packages._"

https://devblogs.microsoft.com/ifdef-windows/windows-community-toolkit-for-project-reunion-0-5/

2022-05-24 20:45 UTC, raymond-wh-leung commented on source/Lottie/LottieVisualOptions.cs
> +namespace MicrosoftToolkit.WinUI.Lottie
Gotcha, good to know. Thx

2022-05-24 20:46 UTC, raymond-wh-leung submitted a review, later dismissed
:shipit:

2022-05-24 22:52 UTC, michael-hawker commented on source/Lottie/LottieVisualOptions.cs
> +namespace MicrosoftToolkit.WinUI.Lottie
@aborziak-ms yes, but the new name is 'CommunityToolkit.WinUI.*` not `MicrosoftToolkit`. Our plan for 8.0 will be to have both the UWP and WinUI packages use the same common namespace, so in your case `CommunityToolkit.WinUI.Lottie`. If you plan to ship a 7.x series it may make sense to keep the split to be consistent. But since this is a new package, you may want to just keep everything consistent now.

Goal with keeping a single namespace across UWP and WinUI 3 is that it makes it easier to consume in XAML and across any projects that want to multi-target both UWP and WinUI 3 simultaneously.

We haven't tried publishing two packages for both UWP and WinUI out of the same branch before, but since you setup a new project file, then it should be fine. We'll have to see in the DevOps feed first to test.

2022-05-24 22:59 UTC, michael-hawker requested changes
Couple of comments and info about where we're heading with the WCT.

Also not sure if you've done an audit for `Dispatcher` usage and `XamlRoot` for the general migration guidance. If things work in XAML Islands today, you should be fine. But always good to check if you missed a move to `DispatcherQueue`.

2022-05-24 22:59 UTC, michael-hawker commented on Lottie-Windows-WinUI3/Lottie-Windows-WinUI3.csproj
> +		<RootNamespace>MicrosoftToolkit.WinUI.Lottie</RootNamespace>
```suggestion
		<RootNamespace>CommunityToolkit.WinUI.Lottie</RootNamespace>
```

`MicrosoftToolkit` is not our root namespace.

2022-05-24 22:59 UTC, michael-hawker commented on source/Lottie/ImageAssetHandler.cs
> +namespace MicrosoftToolkit.WinUI.Lottie
```suggestion
namespace CommunityToolkit.WinUI.Lottie
```

2022-05-24 22:59 UTC, michael-hawker commented on source/Lottie/ImageAssetHandler.cs
>  namespace Microsoft.Toolkit.Uwp.UI.Lottie
If you want to do a 7.x release, probably want to keep the UWP namespace the same. If you want to jump on the 8.0 train early you could just use the same common namespace. (CommunityToolkit.WinUI.Lottie)

The main Windows Community Toolkit 8.0 release that's going to adopt this though probably won't come out until near the end of this year though. We're just setting up our new process in Toolkit Labs for Windows which we then have to adopt and merge all our Toolkit forks together to support UWP and WinUI in one codebase like you're doing here.

2022-05-24 22:59 UTC, michael-hawker commented on Lottie-Windows-WinUI3/Lottie-Windows-WinUI3.csproj
> +		<DefineConstants>Lottie_Windows_WinUI3</DefineConstants>
We're adopting `WINAPPSDK` as our constant in Toolkit Labs for Windows, so if you want to align, you could change this.

2022-05-25 16:19 UTC, michael-hawker commented on Directory.Build.props
> +    <Authors>CommunityToolkit</Authors>
This should stay the same `Microsoft.Toolkit` is our NuGet identity still (just got caught in the mass rename).

2022-05-25 16:21 UTC, aborziak-ms commented on Directory.Build.props
> +    <Authors>CommunityToolkit</Authors>
Oh, ok. Fixed

2022-05-25 16:23 UTC, michael-hawker commented on README.md
> +| 7.1.0 release | main | [![Build Status](https://dev.azure.com/dotnet/WindowsCommunityToolkit/_apis/build/status/CommunityToolkit.WinUI.Lottie?branchName=main)](https://dev.azure.com/dotnet/WindowsC
This devops link may not change: https://dev.azure.com/dotnet/WindowsCommunityToolkit/_apis/build/status/Microsoft.Toolkit.Uwp.UI.Lottie?branchName=main

2022-05-25 16:27 UTC, michael-hawker commented on Lottie-Windows-WinUI3/Lottie-Windows-WinUI3.csproj
> +		<RootNamespace>CommunityToolkit.WinUI.Lottie</RootNamespace>
`AssemblyName` missing here as well? (That's also the fallback for PackageId, so I'm not sure what happens without either.)

2022-05-25 16:29 UTC, michael-hawker commented on Lottie-Windows/Lottie-Windows.csproj
> +    <AssemblyName>CommunityToolkit.WinUI.Lottie</AssemblyName>
```suggestion
    <AssemblyName>CommunityToolkit.WinUI.Lottie</AssemblyName>
    <PackageId>CommunityToolkit.Uwp.Lottie</PackageId>
```

I think it's fine to have the Assembly Name match the namespace still, but we'll want to set the PackageId as otherwise the package names will conflict with the new WinUI 3 one.

2022-05-25 16:35 UTC, aborziak-ms commented on Lottie-Windows-WinUI3/Lottie-Windows-WinUI3.csproj
> +		<RootNamespace>CommunityToolkit.WinUI.Lottie</RootNamespace>
done

2022-05-25 17:18 UTC, merged